require "JC.alpha"
require "JC.autocommands"
require "JC.autopairs"
require "JC.cmp"
require "JC.bufferline"
require "JC.comment"
require "JC.dap"
require "JC.gitsigns"
require "JC.keymap"
require "JC.lualine"
require "JC.nvim-tree"
require "JC.packer"
require "JC.project"
require "JC.set"
require "JC.telescope"
require "JC.toggleterm"
require "JC.treesitter"

